# Generated by Django 4.2.6 on 2023-10-26 13:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('ProjectFinished', models.IntegerField(default=10, max_length=10)),
                ('DigitalAward', models.IntegerField(default=10)),
                ('YearOfExperience', models.IntegerField(default=10)),
                ('HappyCustomer', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('FirstName', models.CharField(default='Piyush', max_length=200)),
                ('LastName', models.CharField(default='Kumar', max_length=200)),
                ('Email', models.EmailField(default='piyushkumarcse44@gmail.com', max_length=200)),
                ('PhoneNo', models.CharField(default='1234567890', max_length=15)),
                ('Photo', models.ImageField(default='images/default.jpg', upload_to='')),
                ('BirthDay', models.DateField(default='2002-06-29')),
                ('LinkedinProfile', models.URLField(default='www.linkedin.com')),
                ('GithubProfile', models.URLField(default='www.github.com')),
                ('CollegeName', models.CharField(default='GoodCollege', max_length=200)),
                ('CollegeAddress', models.CharField(default='india', max_length=200)),
                ('CollegeDegree', models.CharField(blank=True, default='B.tech', max_length=200, null=True)),
                ('CollegeStream', models.CharField(default='Computer Science', max_length=200)),
                ('CollegePassingYear', models.CharField(default='2024', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('GrettingMsg', models.CharField(default='Hello friend!', max_length=200)),
                ('OpenToWork', models.CharField(default='I’m available for freelance work.', max_length=200)),
                ('Description', models.TextField(blank=True, max_length=200, null=True)),
                ('FrontPhoto', models.ImageField(default='images/default.jpg', upload_to='')),
                ('AdditionalInfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MyPortfolioApp.additionalinfo')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MyPortfolioApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitivePlateform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(default='Codechef', max_length=200)),
                ('Photo', models.ImageField(default='images/default.jpg', upload_to='')),
                ('UserId', models.CharField(default='piyush_cse', max_length=200)),
                ('ProfileLink', models.URLField(default='www.codechef.com')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyPortfolioApp.user')),
            ],
        ),
    ]
