# Generated by Django 4.2.6 on 2023-10-26 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolioApp', '0003_remove_profile_experience_alter_experience_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Experience',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='MyPortfolioApp.experience'),
        ),
    ]
