# Generated by Django 4.2.6 on 2023-10-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolioApp', '0005_contactform_experience_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='FrontPhoto1',
            field=models.ImageField(blank=models.ImageField(default='images/default.png', upload_to=''), default='images/default.png', upload_to=''),
        ),
    ]
