# Generated by Django 4.2.6 on 2023-10-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolioApp', '0007_profile_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Description',
            field=models.TextField(),
        ),
    ]
