# Generated by Django 4.2.6 on 2023-10-26 16:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolioApp', '0008_alter_contactform_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(default='Website', max_length=200)),
                ('Price', models.CharField(default='$50', max_length=30)),
                ('logo', models.ImageField(default='images/default.png', upload_to='')),
                ('DiscoveryMore', models.URLField(default='#')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='About',
            field=models.CharField(default='I am a professional Full stack web developer. Feel free to get in touch with me. ', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='Instagram',
            field=models.URLField(default='www.Instagram.com'),
        ),
        migrations.AddField(
            model_name='user',
            name='Pinterest',
            field=models.URLField(default='www.Pintrest.com'),
        ),
        migrations.AddField(
            model_name='user',
            name='Twitter',
            field=models.URLField(default='www.Twitter.com'),
        ),
        migrations.AddField(
            model_name='user',
            name='Youtube',
            field=models.URLField(default='www.Yoube.com'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Experience',
        ),
        migrations.AddField(
            model_name='profile',
            name='Services',
            field=models.ManyToManyField(to='MyPortfolioApp.services'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Experience',
            field=models.ManyToManyField(default=None, to='MyPortfolioApp.experience'),
        ),
    ]
