# Generated by Django 4.2.6 on 2023-10-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolioApp', '0009_services_profile_about_user_instagram_user_pinterest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='DiscoveryMore',
            field=models.URLField(default='wwww.wikipedia.com'),
        ),
    ]
