# Generated by Django 4.2.6 on 2023-10-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolioApp', '0010_services_description_alter_services_discoverymore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='logo',
            field=models.CharField(default='bi-globe', max_length=200),
        ),
    ]
