# Generated by Django 4.2.6 on 2023-10-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolioApp', '0011_alter_services_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Cv',
            field=models.URLField(default='https://drive.google.com/file/d/1DZLy7mRCW3ocaPoy_stLyxq5VrnSmbEF/view?usp=drive_link'),
        ),
    ]
