# Generated by Django 4.2.6 on 2023-10-27 11:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolioApp', '0012_user_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySkill',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(default='c++', max_length=200)),
            ],
        ),
    ]
