# Generated by Django 4.2.6 on 2023-10-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolioApp', '0013_myskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='myskill',
            name='logo',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='MySkill',
            field=models.ManyToManyField(to='MyPortfolioApp.myskill'),
        ),
    ]
