# Generated by Django 4.2.6 on 2023-10-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolioApp', '0014_myskill_logo_profile_myskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myskill',
            name='logo',
            field=models.ImageField(default='#', upload_to=''),
        ),
    ]
