# Generated by Django 4.2.6 on 2023-10-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolioApp', '0015_alter_myskill_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='brand',
            field=models.CharField(default='', max_length=200),
        ),
    ]
