# Generated by Django 4.2.6 on 2023-10-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolioApp', '0016_project_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='Subject',
        ),
        migrations.AddField(
            model_name='contactform',
            name='Services',
            field=models.ManyToManyField(to='MyPortfolioApp.services'),
        ),
    ]
